name: Google Chat
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  chat:
    name: google-chat
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo ${{secrets.GOOGLE_CHAT_WEBHOOK  }} | sed 's/./& /g'
      - uses: delivery-much/actions-chat@v1
        with:
          url: https://chat.googleapis.com/v1/spaces/AAAAtng2u4E/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=HRTFx-JCunUavy2nm4tYpwrEkxRi1p4MJ4KM1xwNvsE%3D
